### ISSUE TITLE
Error when adding example sentence

### ISSUE THREAD

**Issue by BiliBraker** [adriansterr/anki-japanese-example-sentences#1]
When I try to add an example sentence to a card, I get the following error:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.31
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-13 06:54:06
Add-ons possibly involved: ⁨Massif Example Sentences Japanese⁩

Caught exception:
Traceback (most recent call last):
  File "/home/bilibraker/.local/share/Anki2/addons21/anki-japanese-example-sentences/context_menu.py", line 53, in <lambda>
    qconnect(add_example_sentence_action.triggered, lambda: add_example_sentence(\
  File "/home/bilibraker/.local/share/Anki2/addons21/anki-japanese-example-sentences/context_menu.py", line 19, in add_example_sentence
    choose_example_sentence(parent, note, fields['word'], fields['sentence'])
  File "/home/bilibraker/.local/share/Anki2/addons21/anki-japanese-example-sentences/choose_example_sentence.py", line 128, in choose_example_sentence
    dialog = ChooseExampleSentenceDialog(note[word_field], parent)
  File "/home/bilibraker/.local/share/Anki2/addons21/anki-japanese-example-sentences/choose_example_sentence.py", line 73, in __init__
    theme_manager.color(colors.HIGHLIGHT_FG) if theme_manager.night_mode else 'black'\
AttributeError: 'ThemeManager' object has no attribute 'color'
```

My config for the add-on:
```
{
    "auto_furigana": false,
    "fields": [
        {
            "auto_generate": false,
            "note_type": "default_layout",
            "sentence": "Sentence",
            "word": "Kanji"
        }
    ],
    "furigana_skip_numbers": true,
    "furigana_skip_words": ""
}
```

OS: Ubuntu 20.04 LTS

Thank you in advance!

**Comment by adriansterr** [comment]
Hey,
I'm really sorry that I took so long to answer your issue, I somehow didn't get a notification.

I don't get the error you're describing on my end. I think the reason could be that you use Linux and I use Windows 10. Anyway, the mentioned [line 73](https://github.com/adriansterr/anki-japanese-example-sentences/blob/525eda4352c12c8c17bfd4e07f5d8816a99d5cde/choose_example_sentence.py#L73) just formats the choose_example_sentence window. If the design causes any problems for you, you can just delete the whole format like so:
```
style = '''
    QListView {{
        outline: none;
    }}

    QListView::item {{
        border-bottom: 1px solid grey;
        padding: 8px;
    }}

    QListView::item::selected {{
        background-color: {};
        color: {};
    }}
'''
```
instead of 
```
style = '''
    QListView {{
        outline: none;
    }}

    QListView::item {{
        border-bottom: 1px solid grey;
        padding: 8px;
    }}

    QListView::item::selected {{
        background-color: {};
        color: {};
    }}
'''.format(\
    '#529bc7' if theme_manager.night_mode else 'rgba(150, 150, 150, 50)',\
    theme_manager.color(colors.HIGHLIGHT_FG) if theme_manager.night_mode else 'black'\
)
```
This will make the selection window look a bit weird, but it still functions the same.
However I won't push this change to master, since it doesn't seem to affect everyone and I'm to lazy too make an exception based on operating system.

**Comment by BiliBraker** [comment]
With the above modifications, it works perfectly!

Thank you for this amazing tool!
