### ISSUE TITLE
Anki error when clicking the Add/Change Example Sentence button

### ISSUE THREAD

**Issue by Wyzmic** [adriansterr/anki-japanese-example-sentences#2]
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-24 23:14:58
Add-ons possibly involved: ⁨Massif Example Sentences Japanese⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\fred\AppData\Roaming\Anki2\addons21\anki-japanese-example-sentences-master\choose_example_sentence.py", line 146, in <lambda>
    qconnect(action.triggered, lambda: choose_example_sentence_action(browser))
  File "C:\Users\fred\AppData\Roaming\Anki2\addons21\anki-japanese-example-sentences-master\choose_example_sentence.py", line 141, in choose_example_sentence_action
    choose_example_sentence(browser, note, fields['word'], fields['sentence'])
  File "C:\Users\fred\AppData\Roaming\Anki2\addons21\anki-japanese-example-sentences-master\choose_example_sentence.py", line 128, in choose_example_sentence
    dialog = ChooseExampleSentenceDialog(note[word_field], parent)
  File "C:\Users\fred\AppData\Roaming\Anki2\addons21\anki-japanese-example-sentences-master\choose_example_sentence.py", line 73, in __init__
    theme_manager.color(colors.HIGHLIGHT_FG) if theme_manager.night_mode else 'black'\
AttributeError: 'ThemeManager' object has no attribute 'color'

**Comment by adriansterr** [comment]
Hello, thanks for using my add-on!

You're actually the second person already that had this error, but since the last person had Linux and I thought that was the reason, I didn't publish a fix yet. I cannot reproduce your error even though I also have Windows 10, so this time I'll just fix it alltogether. Please check out the branch [fixing](https://github.com/adriansterr/anki-japanese-example-sentences/tree/fixing) and test if that fixes your problem. If it does, I will push it to master later!

Greetings!

**Comment by Wyzmic** [comment]
Hey, great add-on you have! I was using the old example sentence one when I saw your comment that you made one that actually works. It's handy! The fix worked man, appreciate it!

**Comment by Wyzmic** [comment]
Hi, it stopped working again due to Qt5 having been discontinued. When do you think you could update to it?

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22631
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-15 17:35:07

When loading Massif Example Sentences Japanese:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\fred\AppData\Roaming\Anki2\addons21\anki-japanese-example-sentences-fixing\__init__.py", line 1, in <module>
    from . import bulk_sentences, context_menu, choose_example_sentence, example_sentences
  File "C:\Users\fred\AppData\Roaming\Anki2\addons21\anki-japanese-example-sentences-fixing\context_menu.py", line 10, in <module>
    from .choose_example_sentence import choose_example_sentence
  File "C:\Users\fred\AppData\Roaming\Anki2\addons21\anki-japanese-example-sentences-fixing\choose_example_sentence.py", line 7, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'

**Comment by adriansterr** [comment]
Actually Qt5 has not been discontinued. You can download the Qt5 version on the official Anki site:

![download](https://github.com/adriansterr/anki-japanese-example-sentences/assets/53040453/69bf726c-7db1-44ef-80f2-453682d31e61)

And this add-on currently only works with Qt5. I have no idea how to change it to Qt6, so as long as it works, this should do.

**Comment by Wyzmic** [comment]
Oh alright, thanks for pointing it out! Maybe ask chat gpt or something to rewrite the code 😂
